version: 2.1

orbs:
  node: circleci/node@5

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:20.5
    steps:
      - checkout

      # -------------------------
      # Backend dependencies cache
      # -------------------------
      - restore_cache:
          keys:
            - backend-deps-{{ checksum "backend/package-lock.json" }}
            - backend-deps-
      - run:
          name: Install backend dependencies
          command: |
            cd backend
            npm ci
      - save_cache:
          paths:
            - backend/node_modules
          key: backend-deps-{{ checksum "backend/package-lock.json" }}

      # -------------------------
      # Middleware dependencies cache
      # -------------------------
      - restore_cache:
          keys:
            - middleware-deps-{{ checksum "middleware/package-lock.json" }}
            - middleware-deps-
      - run:
          name: Install middleware dependencies
          command: |
            cd middleware
            npm ci
      - save_cache:
          paths:
            - middleware/node_modules
          key: middleware-deps-{{ checksum "middleware/package-lock.json" }}

      # -------------------------
      # Frontend dependencies cache
      # -------------------------
      - restore_cache:
          keys:
            - frontend-deps-{{ checksum "frontend/package-lock.json" }}
            - frontend-deps-
      - run:
          name: Install frontend dependencies
          command: |
            cd frontend
            npm ci
      - save_cache:
          paths:
            - frontend/node_modules
          key: frontend-deps-{{ checksum "frontend/package-lock.json" }}

  test_backend:
    docker:
      - image: cimg/node:20.5
    steps:
      - checkout

      # Install backend and middleware dependencies
      - run:
          name: Install backend and middleware dependencies
          command: |
            cd backend && npm ci
            cd ../middleware && npm ci

      # Make Jest executable
      - run:
          name: Make Jest executable
          command: chmod +x ./backend/node_modules/.bin/jest

      # Run backend tests
      - run:
          name: Run backend tests
          command: cd backend && npx jest --ci --coverage

  test_frontend:
    docker:
      - image: cimg/node:20.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-deps-{{ checksum "frontend/package-lock.json" }}
            - frontend-deps-
      - run:
          name: Install frontend dependencies
          command: cd frontend && npm ci
      - save_cache:
          paths:
            - frontend/node_modules
          key: frontend-deps-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: Run frontend tests
          command: cd frontend && npm test -- --watchAll=false --ci --coverage

workflows:
  version: 2
  test-and-build:
    jobs:
      - install_dependencies
      - test_backend:
          requires:
            - install_dependencies
      - test_frontend:
          requires:
            - install_dependencies
