version: 2.1

orbs:
  node: circleci/node@5

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:20.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "backend/package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install backend dependencies
          command: |
            cd backend
            npm ci
      - save_cache:
          paths:
            - backend/node_modules
          key: v1-dependencies-{{ checksum "backend/package-lock.json" }}
      - restore_cache:
          keys:
            - v1-frontend-dependencies-{{ checksum "frontend/package-lock.json" }}
            - v1-frontend-dependencies-
      - run:
          name: Install frontend dependencies
          command: |
            cd frontend
            npm ci
      - save_cache:
          paths:
            - frontend/node_modules
          key: v1-frontend-dependencies-{{ checksum "frontend/package-lock.json" }}

  test_backend:
    docker:
      - image: cimg/node:20.5
    steps:
      - checkout
      - run:
          name: Run backend tests
          command: |
            cd backend
            npm test

  test_frontend:
    docker:
      - image: cimg/node:20.5
    steps:
      - checkout
      - run:
          name: Run frontend tests
          command: |
            cd frontend
            npm test

workflows:
  version: 2
  test-and-build:
    jobs:
      - install_dependencies
      - test_backend:
          requires:
            - install_dependencies
      - test_frontend:
          requires:
            - install_dependencies
